### PR TITLE
chore!: build with TypeScript v5.3.3

### LINKED ISSUE #189: chore: use TypeScript v5 to build
Usage of TS v5 generates tsc errors: see #185 and #186

```
Version 5.0.2
Error: src/view/mixins/ValidationMixin.ts(324,10): error TS2365: Operator '>' cannot be applied to types 'number' and 'string | number'.
Error: src/view/mixins/ValidationMixin.ts(330,10): error TS2365: Operator '>' cannot be applied to types 'number' and 'string | number'.
Error: src/view/other/Multiplicity.ts(160,45): error TS2365: Operator '>=' cannot be applied to types 'number' and 'string | number'.
Error: src/view/other/Multiplicity.ts(161,47): error TS2365: Operator '>=' cannot be applied to types 'number' and 'string | number'.
Error: Process completed with exit code 2.
```

To review as part of this issue
- the `html` package declares a typescript dependency whereas it is not using TypeScript
- the `core` package declares a typescript dependency to workaround a TS error because TS v5 was resolved instead of v4 (#186)

### PR DESCRIPTION
**Pull request by tbouffard**
As TypeScript v5 detects more errors, the version bump requires to update the `Multiplicity` class. It now only accepts number for the `max` property. Previously, it accepted a special string value, but TypeScript v5 now complains when comparing a number with a string. So, as the `max` property is used in number comparisons, it must only accept number.

Also bump some development dependencies to get better support for TypeScript v5.
  - `typedoc` from 0.23 to 0.25 
  - `storybook` from 7.4  to 7.6

BREAKING CHANGE:  it is no longer possible to pass an 'n' value for the `max` property of the `Multiplicity` class. Pass `null` instead to have the same effect.

Closes #189

### CODE REVIEW

File: CHANGELOG.md [hunk 1]
```diff
@@ -1,5 +1,11 @@
 # `maxGraph` Change Log
 
+## UNRELEASED
+
+**Breaking Changes**
+- it is no more possible to pass a 'n' value for the `max` property of the `Multiplicity` class. Pass `null` instead to have the same effect.
+- the UMD bundle is no more provided in the npm package.
```
Comment (tbouffard) [inline CHANGELOG.md]: To remove, done in v0.5.0

Comment (tbouffard) [inline CHANGELOG.md]:
```suggestion
```

Comment (tbouffard) [reply CHANGELOG.md]: done in 46c47b0
